---
daq_options:
 compressRawData: yes
 nEvent: 500
 externalChargeInjection: yes
 acquisitionType: sweep
 channelIds: []
 channelIdsToMask: [[3,22],[],[],[]]
 injectionDAC: 1000
 pulseDelay: 47
 preampFeedbackCapacitance: 8 
 totDACThreshold: 200
 toaDACThreshold: 230
 shapingTime: 35
glb_options:
 moduleNumber: 63
 outputRawDataPath: data
 outputYamlPath: yaml
 storeYamlFile: yes
 startServerManually: no
 serverIpAdress: localhost
 serverCodePath: /home/pi/rpi-daq
...
